version: '3.8'

services:
  # Development environment
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"   # Web app
      - "5173:5173"   # Vite dev server
      - "8081:8081"   # Expo dev server
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
    depends_on:
      - supabase
      - redis

  # Supabase local development
  supabase:
    image: supabase/postgres:15.1.0.117
    ports:
      - "54322:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    volumes:
      - supabase_db:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Nginx for production-like testing
  nginx:
    build:
      context: .
      target: web-production
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}
    ports:
      - "8080:80"
    profiles:
      - production

  # Test runner
  test:
    build:
      context: .
      target: test
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    profiles:
      - test

volumes:
  supabase_db:
  redis_data:

networks:
  default:
    name: sakina-network
